version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/groovy-api
hooks:
  BeforeInstall:
    - location: infra/scripts/cleanup.sh
      runas: root
  AfterInstall:
    - location: infra/scripts/ssm2env.sh
      runas: root
    - location: infra/scripts/configure.sh
      runas: root
  ApplicationStart:
    - location: infra/scripts/start.sh
      runas: root
