# Generated by Django 4.0.2 on 2022-03-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REFUSED', 'REFUSED'), ('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING')], max_length=15)),
                ('status_changed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'friend_request',
            },
        ),
    ]
