# Generated by Django 4.0.2 on 2022-04-08 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0002_auto_20220328_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('REFUSED', 'REFUSED'), ('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING')],
                                   default='PENDING', max_length=15),
        ),
    ]
