# Generated by Django 4.0.2 on 2022-05-24 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('friend', '0003_alter_friend_friend_alter_friendrequest_status'),
        ('friend', '0004_alter_friend_friend'),
        ('friend', '0005_alter_friend_friend'),
    ]

    operations = [
    ]
