# Generated by Django 4.0.2 on 2022-03-15 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularchat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_chat_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_chat_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatroom',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='chatroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groupchatroom'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
