# Generated by Django 4.0.2 on 2022-04-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_auto_20220328_0135"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularchat",
            name="is_join_request_message",
            field=models.BooleanField(default=False),
        ),
    ]
