# Generated by Django 4.0.2 on 2022-04-05 22:37

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_regularchat_is_join_request_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('is_join_request_message', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'personal_chat',
            },
        ),
        migrations.CreateModel(
            name='PersonalChatroom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receiver', models.ForeignKey(on_delete=models.SET(chat.models.user_inexistent), related_name='personal_chatroom_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=models.SET(chat.models.user_inexistent), related_name='personal_chatroom_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_chat', to='chat.groupchatroom'),
        ),
        migrations.DeleteModel(
            name='RegularChat',
        ),
        migrations.AddField(
            model_name='personalchat',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatroom', to='chat.personalchatroom'),
        ),
        migrations.AddField(
            model_name='personalchat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_chat_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalchat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_chat_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='personalchatroom',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_chatroom'),
        ),
    ]
