# Generated by Django 4.0.2 on 2022-04-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_quota_alter_group_status_changed_at'),
        ('chat', '0005_alter_personalchat_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chatroom', to='group.group'),
        ),
        migrations.CreateModel(
            name='PersonalChatroomNotice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='chat.personalchatroom')),
                ('pinned_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_chat', to='chat.personalchat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupChatroomNotice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='chat.groupchatroom')),
                ('pinned_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_chat', to='chat.groupchat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
