# Generated by Django 4.0.2 on 2022-05-24 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_regularchat_is_join_request_message'),
        ('chat', '0005_alter_personalchat_table_and_more'),
        ('chat', '0006_alter_groupchatroom_group_personalchatroomnotice_and_more'),
    ]

    operations = [
    ]
