# Generated by Django 4.0.2 on 2022-05-24 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0007_merge_20220524_1423'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupchatroomnotice',
            table='group_chatroom_notice',
        ),
        migrations.DeleteModel(
            name='PersonalChatroomNotice',
        ),
    ]
