# Generated by Django 3.1.5 on 2022-03-28 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=32)),
                ("content", models.CharField(max_length=1000)),
                ("quota", models.PositiveSmallIntegerField(null=True)),
                ("has_no_quota", models.BooleanField(default=False)),
                ("is_approval_needed", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "group",
            },
        ),
        migrations.CreateModel(
            name="GroupBookmark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "group_bookmark",
            },
        ),
        migrations.CreateModel(
            name="GroupJoinRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REFUSED", "REFUSED"),
                            ("ACCEPTED", "ACCEPTED"),
                            ("PENDING", "PENDING"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "group_join_request",
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="group.group",
                    ),
                ),
            ],
            options={
                "db_table": "group_member",
            },
        ),
    ]
