# Generated by Django 4.0.2 on 2022-04-01 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0002_auto_20220328_0135"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[("OPENED", "OPENED"), ("CLOSED", "CLOSED"), ("FULL", "FULL")],
                default="OPENED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="status_changed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="groupjoinrequest",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="join_requests",
                to="group.group",
            ),
        ),
        migrations.RemoveField(
            model_name="groupjoinrequest",
            name="requestor",
        ),
        migrations.AddField(
            model_name="groupjoinrequest",
            name="requestor",
            field=models.ManyToManyField(
                related_name="join_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="member",
        ),
        migrations.AddField(
            model_name="groupmember",
            name="member",
            field=models.ManyToManyField(
                related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
