# Generated by Django 4.0.2 on 2022-04-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_status_group_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='quota',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
