# Generated by Django 4.0.2 on 2022-05-24 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('group', '0003_group_status_group_status_changed_at_and_more'),
        ('group', '0004_alter_group_quota_alter_group_status_changed_at'),
    ]

    operations = [
    ]
