# Generated by Django 3.1.5 on 2022-03-28 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=64, null=True, unique=True)),
                ('name', models.CharField(default='', help_text='실명', max_length=20)),
                ('nickname', models.CharField(blank=True, default='', help_text='서비스 상에서 사용되는 이름', max_length=20)),
                ('gender', models.CharField(choices=[(None, 'NONE'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=8)),
                ('birth_date', models.DateField(null=True)),
                ('is_university_confirmed', models.BooleanField(default=False)),
                ('university_confirmed_at', models.DateTimeField(null=True)),
                ('admission_class', models.SmallIntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2022)),
                ('grade', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('profile_image_url', models.URLField(blank=True, default='', max_length=256)),
                ('thumbnail_image_url', models.URLField(blank=True, default='', max_length=256)),
                ('is_service_terms_agreed', models.BooleanField(default=False)),
                ('is_push_allowed', models.BooleanField(default=False)),
                ('push_id', models.CharField(max_length=64, null=True)),
                ('login_attempt_at', models.DateTimeField(null=True)),
                ('last_login_at', models.DateTimeField(null=True)),
                ('app_version', models.CharField(max_length=16, null=True)),
                ('auth_token', models.CharField(max_length=128, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_reason', models.CharField(blank=True, choices=[('기타', '기타')], max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_suggestion',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.university'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email',)},
        ),
    ]
