# Generated by Django 4.0.2 on 2022-04-01 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="user.university",
            ),
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("Friend Request Received", "FRIEND REQUEST RECEIVED"),
                            ("Friend Request Accepted", "FRIEND REQUEST ACCEPTED"),
                            ("Join Request Received", "JOIN REQUEST RECEIVED"),
                            ("Join Request Accepted", "JOIN REQUEST ACCEPTED"),
                            ("Join Request Refused", "JOIN REQUEST REFUSED"),
                            ("General", "GENERAL"),
                            ("Promotion", "PROMOTION"),
                            ("Other", "OTHER"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.CharField(max_length=300)),
                ("redirect_url", models.URLField(blank=True, max_length=30, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notification",
            },
        ),
    ]
