# Generated by Django 4.0.2 on 2022-05-16 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_remove_user_name_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_university_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(choices=[('YONSEI', 'YONSEI')], default='YONSEI', max_length=50),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('FRIEND REQUEST RECEIVED', 'FRIEND REQUEST RECEIVED'),
                                            ('FRIEND REQUEST ACCEPTED', 'FRIEND REQUEST ACCEPTED'),
                                            ('JOIN REQUEST RECEIVED', 'JOIN REQUEST RECEIVED'),
                                            ('JOIN REQUEST ACCEPTED', 'JOIN REQUEST ACCEPTED'),
                                            ('JOIN REQUEST REFUSED', 'JOIN REQUEST REFUSED'), ('GENERAL', 'GENERAL'),
                                            ('PROMOTION', 'PROMOTION'), ('OTHER', 'OTHER')], max_length=30),
        ),
        migrations.CreateModel(
            name='UniversityManualVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verification_method', models.CharField(
                    choices=[('STUDENT ID', 'STUDENT ID'), ('PROOF OF ENROLLMENT', 'PROOF OF ENROLLMENT'),
                             ('PROOF OF ACCEPTANCE', 'PROOF OF ACCEPTANCE')], max_length=20)),
                ('verification_img_url', models.URLField(blank=True, default='', max_length=256)),
                ('verification_status',
                 models.CharField(choices=[('REFUSED', 'REFUSED'), ('ACCEPTED', 'ACCEPTED'), ('PENDING', 'PENDING')],
                                  default='PENDING', max_length=15)),
                ('status_changed_at', models.DateTimeField(null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
