# Generated by Django 4.0.2 on 2022-05-24 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_alter_user_university_usernotification'),
        ('user', '0003_remove_user_name_user_is_active'),
        ('user', '0004_remove_user_is_active_user_is_university_email_and_more'),
        ('user', '0005_remove_user_is_deleted_alter_user_deleted_at'),
        ('user', '0006_alter_user_deleted_at'),
    ]

    operations = [
    ]
